/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.swing.componentes;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

import java.awt.Frame;

/**
 *
 * @author ASRock
 */
public class topMenuLogin extends javax.swing.JPanel {
    private int mouseX;
    private int mouseY;

    /**
     * Creates new form topMenu
     */
    public topMenuLogin() {
        initComponents();
    }

    public void setMenuFunctions(JFrame window, String title){
        titleLbl.setText(title);
        exitLbl.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                System.exit(0);
            }
        });
        minimizeLbl.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                window.setState(Frame.ICONIFIED);
            }
        });
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                mouseX = evt.getX();
                mouseY = evt.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                int coordX = evt.getXOnScreen();
                int coordY = evt.getYOnScreen();
                window.setLocation(coordX - mouseX, coordY - mouseY);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionLayout = new javax.swing.JPanel();
        minimizeLbl = new javax.swing.JLabel();
        exitLbl = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 51, 60));
        setLayout(new java.awt.BorderLayout());

        actionLayout.setOpaque(false);

        minimizeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/swing/componentes/images/icons8_minus_18px_1.png"))); // NOI18N
        minimizeLbl.setAlignmentX(0.5F);

        exitLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/swing/componentes/images/icons8_multiply_18px_1.png"))); // NOI18N
        exitLbl.setAlignmentX(0.5F);

        javax.swing.GroupLayout actionLayoutLayout = new javax.swing.GroupLayout(actionLayout);
        actionLayout.setLayout(actionLayoutLayout);
        actionLayoutLayout.setHorizontalGroup(
            actionLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionLayoutLayout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addComponent(minimizeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLbl)
                .addContainerGap())
        );
        actionLayoutLayout.setVerticalGroup(
            actionLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionLayoutLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(actionLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitLbl)
                    .addComponent(minimizeLbl))
                .addContainerGap())
        );

        add(actionLayout, java.awt.BorderLayout.LINE_END);

        title.setOpaque(false);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Title");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLbl)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(title, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionLayout;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel minimizeLbl;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    
}
